# Generated by Django 5.1.2 on 2024-10-30 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='localizacion.departamento')),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.departamento')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='localizacion.provincia')),
            ],
            options={
                'db_table': 'distrito',
            },
        ),
    ]
