# Generated by Django 5.1.2 on 2024-11-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
