# Generated by Django 5.0.9 on 2025-01-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='fecha_llegada',
            field=models.DateTimeField(null=True),
        ),
    ]
