# Generated by Django 5.1.2 on 2024-10-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
