# Generated by Django 5.0.9 on 2025-02-04 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0002_despacho_fecha_llegada'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_de_actualizacion', models.DateTimeField(auto_now=True)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importaciones.despacho')),
            ],
            options={
                'db_table': 'gastos_extra',
            },
        ),
    ]
