# Generated by Django 5.0.9 on 2025-02-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0003_gastosextra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastosextra',
            old_name='decripcion',
            new_name='descripcion',
        ),
    ]
