# Generated by Django 5.0.9 on 2025-03-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0005_alter_ordencompradespacho_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='archivo_pdf',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
    ]
